app = "production-teentix-org"
kill_signal = "SIGTERM"
kill_timeout = 5

[processes]
  app = ""
  queue = "queue-runner"

[env]
  # The environment Craft is currently running in ('dev', 'staging', 'production', etc.)
  ENVIRONMENT = "production"

  # Craft general settings
  ALLOW_UPDATES = 0
  ALLOW_ADMIN_CHANGES = 1
  BACKUP_ON_UPDATE = 0
  DEV_MODE = 0
  ENABLE_TEMPLATE_CACHING = 1
  IS_SYSTEM_LIVE = 1
  RUN_QUEUE_AUTOMATICALLY = 1

  # Craft database settings
  DB_DRIVER = "mysql"
  DB_SERVER = "production-teentix-mysql.internal"
  DB_USER = "teentixadmin"
  DB_DATABASE="teentix_prod"
  DB_SCHEMA="public"
  DB_TABLE_PREFIX=""
  DB_PORT="3306"

  # Redis cache settings
  REDIS_HOST="production-teentix-redis.internal"
  REDIS_PORT="6379"
  REDIS_SSL="false"

  # URL & path settings
  ASSETS_URL="https://www.teentix.org/"
  ASSETS_URL_SEA="https://seattle.teentix.org/"
  ASSETS_URL_LA="https://la.teentix.org/"
  SITE_URL="https://www.teentix.org/"
  SITE_URL_SEA="https://seattle.teentix.org/"
  SITE_URL_LA="https://la.teentix.org/"
  BASE_CP_URL="https://admin.teentix.org/"
  COOKIE_DOMAIN=".teentix.org"
  WEB_ROOT_PATH="/app/html"

  AZURE_BLOB_IMAGES_URL="https://productionteentixassets.blob.core.windows.net/production-assets"
  AZURE_BLOB_STORAGE_CONTAINER="production-assets"

  # ADMIN EMAILS
  EMAIL_ADMIN="info@teentix.org"
  EMAIL_ADMIN_LA="info@la.teentix.org"

  # Google Analytics settings
  GA_TRACKING_ID="G-E2PX6F4X50"

  #Mailchimp Keys
  MAILCHIMP_LIST_NEWSLETTER="c51b9e3d2f"
  LA_MAILCHIMP_LIST_NEWSLETTER="128e90aeae"

  # MAILGUN SMTP Settings
  MAILGUN_USERNAME="postmaster@sandbox7dc261cf78fd46389d68c09d2d74d792.mailgun.org"

  # SENDGRID SMTP Settings
  SENDGRID_USERNAME="apikey"

  # MANDRILL API Seetings
  MANDRILL_USERNAME="TeenTix"

  NEW_RELIC_AGENT_ENABLED="true"
  NEW_RELIC_APP_NAME="production-teentix-org"
  NEW_RELIC_LOG_LEVEL="warning"

  PHP_MEMORY_LIMIT="1024M"
  PHP_MAX_EXECUTION_TIME="120"
  PHP_UPLOAD_MAX_FILESIZE="20M"
  PHP_MAX_INPUT_VARS="1000"
  PHP_POST_MAX_SIZE="32M"
  PHP_OPCACHE_ENABLE="1"
  PHP_OPCACHE_REVALIDATE_FREQ="0"
  PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"
  PHP_OPCACHE_MAX_ACCELERATED_FILES="10000"
  PHP_OPCACHE_MEMORY_CONSUMPTION="128"
  PHP_OPCACHE_MAX_WASTED_PERCENTAGE="10"
  PHP_OPCACHE_INTERNED_STRINGS_BUFFER="16"
  PHP_OPCACHE_FAST_SHUTDOWN="0"

[build]
  dockerfile = "docker/Dockerfile"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["app"]
  internal_port = 80
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    method = "GET"
    path = "/actions/app/health-check"
    protocol = "http"
    timeout = "3s"
