field: 019bfad1-7fee-4969-a0ce-4106539e4f9b # Flexible Content
fieldLayouts:
  91ade4e4-7e6a-4fe8-81f7-c2183a55d3f2:
    tabs:
      -
        elements:
          -
            fieldUid: 73619ef2-831b-4cbf-9da3-9d261470f0ba # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97462408-5739-4c26-83b8-755f42a551cc
            warning: null
            width: 100
          -
            fieldUid: 04e552e5-3475-4c31-af48-0c83a705b533 # Content Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09d050b5-cf40-4971-8385-856c45e9e7ae
            warning: null
            width: 100
          -
            fieldUid: d5c997f3-7790-4a12-a113-ceb567221d44 # Content Main
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ccf646-a2b7-455a-94be-8f3ac9a2e966
            warning: null
            width: 100
          -
            fieldUid: 89d3afdf-0aa9-4f44-883c-49b5f71761eb # Sidebar Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c77fa44-80fc-4b65-9e01-ce818d26b334
            warning: null
            width: 100
          -
            fieldUid: 60ab3f1e-c223-44f6-bf59-9eae13970e0c # Content Sidebar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87d5a7f2-db44-4737-9b49-6f3f4797a8c0
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: de92c41d-4884-4109-8449-89fe91ea51d0
fields:
  04e552e5-3475-4c31-af48-0c83a705b533: # Content Position
    contentColumnType: string
    fieldGroup: null
    handle: contentPosition
    instructions: ''
    name: 'Content Position'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  60ab3f1e-c223-44f6-bf59-9eae13970e0c: # Content Sidebar
    contentColumnType: text
    fieldGroup: null
    handle: contentSidebar
    instructions: ''
    name: 'Content Sidebar'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - ff4a3796-5f38-4dbb-8328-85026951b987 # SEA Page Images
        - bb8ba4ad-ead4-4ad1-a642-2bc2b11c7beb # SEA Partner Images
        - 834d8a22-ae60-4d04-9fd2-a0924a7e93f2 # SEA Ad Images
        - a16a3316-a22e-4c0f-82e4-fe841faf49ce # SEA General Images
        - d8eeb3df-3c65-4ed9-b943-c95348bd3f50 # SEA Sponsor Logos
        - 7f7bf724-7909-4699-b70a-5cd496c314bb # LA Page Images
        - 0543ea8d-9bf0-4033-bb9a-bae51d9860cf # LA Partner Images
        - a6e1f43e-7d92-4454-b86e-9b57856d3c34 # LA Ad Images
        - d8052c64-2464-4aa2-8b41-9f106bc1d1f6 # LA General Images
        - 5ec9bf08-ecd8-45fc-9476-42230de4ea06 # LA Sponsor Logos
      ckeConfig: d57b7f37-d318-4280-b2f7-d898d3049383 # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: ''
      purifyHtml: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  89d3afdf-0aa9-4f44-883c-49b5f71761eb: # Sidebar Background
    contentColumnType: string
    fieldGroup: null
    handle: sidebarBackground
    instructions: ''
    name: 'Sidebar Background'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Gray
            -
              - value
              - gray
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  73619ef2-831b-4cbf-9da3-9d261470f0ba: # Header
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d5c997f3-7790-4a12-a113-ceb567221d44: # Content Main
    contentColumnType: text
    fieldGroup: null
    handle: contentMain
    instructions: ''
    name: 'Content Main'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - ff4a3796-5f38-4dbb-8328-85026951b987 # SEA Page Images
        - bb8ba4ad-ead4-4ad1-a642-2bc2b11c7beb # SEA Partner Images
        - 834d8a22-ae60-4d04-9fd2-a0924a7e93f2 # SEA Ad Images
        - a16a3316-a22e-4c0f-82e4-fe841faf49ce # SEA General Images
        - d8eeb3df-3c65-4ed9-b943-c95348bd3f50 # SEA Sponsor Logos
        - 7f7bf724-7909-4699-b70a-5cd496c314bb # LA Page Images
        - 0543ea8d-9bf0-4033-bb9a-bae51d9860cf # LA Partner Images
        - a6e1f43e-7d92-4454-b86e-9b57856d3c34 # LA Ad Images
        - d8052c64-2464-4aa2-8b41-9f106bc1d1f6 # LA General Images
        - 5ec9bf08-ecd8-45fc-9476-42230de4ea06 # LA Sponsor Logos
      ckeConfig: d57b7f37-d318-4280-b2f7-d898d3049383 # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: Standard.json
      purifyHtml: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: contentSidebar
name: 'Content with Sidebar'
sortOrder: 1
