fieldLayouts:
  af1c0f34-dc6c-4370-a012-43551b445367:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5a9e2025-a195-4b99-8963-f3a633a9a9b3
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: "## Ad dates\r\n\r\nUse the entry **Post Date** and **Expiry Date** to set campaign start and end dates."
            type: craft\fieldlayoutelements\Tip
            uid: cdc3e077-4ba7-46ed-a54f-65fec4bd438d
            userCondition: null
          -
            elementCondition: null
            fieldUid: d8f6df29-8bd5-4eec-8ba6-5fa033c72a49 # Advertiser Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2be90b5a-97a3-4aaf-9092-8f157b349b43
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b0eceb4f-b5bc-4e49-b49e-33a7974ea2ec # Banner Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82ccd241-c820-4092-a2f1-195fc9f1b709
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d094b0a5-1093-4ecb-a904-eef7fc65ea3e # Banner Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c434676-a09a-4c39-8e75-5df5dd57d148
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6b825aa-dca9-4c38-ae85-7467c61b8aec # Banner 300x250 or 600x500
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 027ecc09-679f-4230-95b6-19a6b858ccc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da66bcf0-09d4-4be6-8293-a34eb5076824 # Banner 300x600
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6d4cc1b-d26f-4ff7-8642-1435f2e16b7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46a70627-1c9f-42d0-99e5-06d393e0b8d2 # Banner 1000x50
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e36bcf3f-6f02-4026-acb0-6a82476f320c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aeb3b289-45fb-4c02-b8b7-db407750d5c1 # Homepage Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a9a3b71-bda9-4b67-96a0-a786ebed41ea
            userCondition: null
            warning: null
            width: 100
        name: Ads
        uid: b0d2d88a-5d9c-477a-a274-a9c9aa0f7575
        userCondition: null
handle: ads
hasTitleField: true
name: Ads
section: 8de01c48-93b4-49f3-8137-bd63a4dc7f5d # SEA Ads
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
