fieldLayouts:
  cae8a5ad-95d1-43f9-8b3f-990bb57d1008:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66309a93-bd05-4200-8b7d-ce412c59e061
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b0828cb-f1af-4d35-a74a-ce937f8e99bd # User
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3a6cd07-4992-4b53-b842-58a970b7568c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48eb74de-92d8-4d65-8b05-06dcb60dc50d # Event
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff0d81bb-0621-4059-8172-c2f160bac67f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1718532f-9c0b-4b5e-8a4c-91468adaea98 # Venue
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e3fe6e1-30aa-43e1-9a4f-63abe63d77d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad344599-5214-4547-9cfa-ba883a0dea43 # Showtime
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e1d6f3d-b9ed-42d4-857c-1c38b53a4129
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22f15960-9f20-4eb1-9234-fe848b4bcb10 # Unlisted Showtime?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e63b81e6-1f46-4956-8220-e789ef23d6ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b00923a3-6edc-40db-b9d4-c4d390c2abe9 # 2 for ?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3dab8e4-2a84-4aad-b3db-0c6070f1bd75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce8c0355-8267-4664-bf52-1d74a6fe3ffe # Number of Guests
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8fd2d74-deba-4140-884a-c544151d53dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81189a7-4d65-47e9-bf68-b5e97de1c1ae # Who’s with you?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 357b0959-a458-4f37-a6e5-49b58a914f00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de6b6fca-d855-44ff-8557-3f044be49dab # Transportation
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 854ead4f-3851-4f1f-b52d-1ee894a25235
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58f12c41-4aca-4bd2-8096-6dda9977becb
        userCondition: null
handle: checkins
hasTitleField: false
name: Check-Ins
section: ede8a2ce-d955-4415-9cca-155641fbd853 # SEA Check-Ins
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: 'Check-In @ {checkinShowtime|datetime} (User {checkinUser|first.id})'
titleTranslationKeyFormat: null
titleTranslationMethod: site
