fieldLayouts:
  364d5f1f-d07e-4e82-9803-c78bff1f9f4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 848f6b1a-dc32-4c1a-820b-0088b8855817
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5764896d-54f2-425b-b36e-4278f5440071 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41bb1f70-4ad4-4530-b0bc-89d448f8955f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1dc4fb76-f668-47e6-aee9-279059fad8b9
        userCondition: null
handle: la_partnersIndex
hasTitleField: true
name: 'LA Partners Index'
section: 52d4dc08-82de-4335-873c-84ed0ed6d8f2 # LA Partners Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
