fieldLayouts:
  b43e1688-ebcd-4bca-92f2-a05fc98566d5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ace9eb79-f56a-4299-ae52-ee1f952066cf
            warning: null
            width: 100
          -
            fieldUid: 5764896d-54f2-425b-b36e-4278f5440071 # Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52b80c66-b65b-49d4-bb9a-672d217fc3ea
            warning: null
            width: 100
          -
            fieldUid: a90c52fa-0196-4670-b873-28510ea21097 # Form
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0df3d2f-77ec-4bbb-96fe-715e7047bda1
            warning: null
            width: 100
          -
            fieldUid: 03d3b7e5-9fca-4789-b7ba-ca374aa1b19d # Sidebar
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa14e3b0-cdd3-44ba-a02b-1fe095af80db
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: 430c202f-44c0-4636-82e7-e7510fe9e922
      -
        elements:
          -
            fieldUid: 12f0e18b-8472-48c3-b1ea-8d447c21c8ec
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 072d6184-cae7-4044-b0dc-83bdc570019e
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
        uid: 61518c60-2353-42b8-9705-224865218ea6
handle: newsletter
hasTitleField: true
name: Newsletter
section: ea460316-fa92-49f2-824c-ab3a7284aeeb # SEA Pages
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
