fieldLayouts:
  b0e21b28-4928-4277-a163-622c147a4d94:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef18556f-9eaf-4028-9e55-05e421174b35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5764896d-54f2-425b-b36e-4278f5440071 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b922be7a-7ead-4a93-8054-6835cd951f50
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 432b3334-e8da-45d7-962c-e89a9797de19
        userCondition: null
handle: partnersIndex
hasTitleField: true
name: 'SEA Partners Index'
section: 559cd26f-f4d3-4a7c-a26d-da69e18446dd # SEA Partners Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
