fieldLayouts:
  06716b6e-a77c-49b0-8ff3-4b530aa00b8f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4a4516c9-bff8-4b54-a7ab-5ed3b883316c
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: 6f1691bb-587b-4995-8ea3-42cc68cf3f20
handle: eventType
name: 'Event Genre'
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    hasUrls: false
    template: null
    uriFormat: null
  7d81a2c3-37f0-4c8e-ae20-7d3ab5055184: # TeenTix LA
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: e5fb9a0d-bcc3-4db9-aadb-532310651286
