fieldLayouts:
  ea8f4978-fc2b-4b87-ab0c-4b53e6e6c9a1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f961f714-0445-472c-94fd-725f7f9c2e61
            warning: null
            width: 100
        name: Content
        sortOrder: 1
        uid: 341127bc-52d8-43db-8019-aa05dab23f83
handle: ticketType
name: 'Ticket Type'
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    hasUrls: false
    template: null
    uriFormat: null
  7d81a2c3-37f0-4c8e-ae20-7d3ab5055184: # TeenTix LA
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 00c258fa-d24b-428a-bf06-1c8ed60d0db2
