handle: la_sidebarAbout
instructions: ''
maxNodes: ''
name: 'LA Sidebar About'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: none
siteSettings:
  7d81a2c3-37f0-4c8e-ae20-7d3ab5055184: # TeenTix LA
    enabled: '1'
sortOrder: 9
structure:
  maxLevels: null
  uid: 2952aac0-2a77-4ed1-a7cb-c6dbbb06c3f7
