handle: sidebarSupport
instructions: ''
maxNodes: ''
name: 'Sea Sidebar Support'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: none
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    enabled: '1'
sortOrder: 6
structure:
  maxLevels: '1'
  uid: 44f0f578-be55-4d07-9d52-a7ff71c921ea
