allowRepeatingEvents: true
color: '#cc0000'
description: ''
descriptionFieldHandle: '0'
fieldLayout:
  tabs:
    -
      elementCondition: null
      elements:
        -
          elementCondition: null
          fieldUid: 7bc6a511-10a7-4729-b23e-340511a91a7c # Related Event
          instructions: null
          label: null
          required: true
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 76f2e50f-266b-4e4f-8b16-37bff4ba0e45
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: edd758f8-e0ec-4ef3-86af-51690335ece7 # Event Genre
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: e5654eb7-31e5-4c77-81da-139fa0615eee
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 9e9abb47-ea9a-4f12-96b5-d915fab1218f # Event Category
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: cdb21c9d-a1e8-46fb-9b64-9d0ea0f72b27
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 0968ba9e-9a4c-4238-a65b-ad3a323f8cca # Event Partner
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: a91d77c9-b8eb-4611-adf8-da49d0e70b54
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: b0a408b3-9d0d-409e-b9a9-564c0ecb283c # Venue
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 325db2f6-a4c4-4d01-8b8a-9b13d24c8107
          userCondition: null
          warning: null
          width: 100
      name: Content
      uid: 069b6a72-475b-4eab-bac1-bbcde7050184
      userCondition: null
    -
      elementCondition: null
      elements:
        -
          dismissible: false
          elementCondition: null
          style: tip
          tip: "## Events with Multiple Start Times\r\nIf the event has multiple start times (for example: 2pm showing and 7pm showing or weekends at 7pm with a sunday matinee) you will need to add the additional start times as a separate entry under \"Calendar: Events Additional Time\".\r\n\r\n**Event Title**\r\nThe title is for internal use only, so it is recommended to use the event name and start time of the event.\r\n\r\n**Event Dates**\r\nEnter the first date and start time of the additional event time and select repeat rules.\r\n\r\n**Related Event**\r\nYou must select the original event that this additional time is related to. Many events have the same name, so double check the event date and location of the event you are selecting to make sure it is the correct one.\r\n\r\n**Event Genre, Category, Partner and Venue**\r\nIn order for the additional times to display in the filtered monthly calendars, and on Partner and Venue pages, you need to select the corresponding Event Genre, Category, Partner and Venue. The rest of the event information will be pulled from the event you selected under **Related Event**."
          type: craft\fieldlayoutelements\Tip
          uid: 45692807-5a76-4471-a88f-ff4a61b8bf54
          userCondition: null
      name: Help
      uid: 9e389d6e-d35f-4ebc-8c03-2aec66c7ee72
      userCondition: null
  uid: 6e470e57-ae6a-4d3f-8f3b-310d713c3ad4
handle: eventsAdditional
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: '0'
name: 'Events Additional Time'
siteSettings:
  2193a20a-abdd-4d56-9bfc-866ac8a65464:
    enabledByDefault: true
    hasUrls: false
    siteId: 0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0 # TeenTix
    template: null
    uriFormat: null
titleFormat: ''
titleLabel: Title
titleTranslationKeyFormat: ''
titleTranslationMethod: site
