allowRepeatingEvents: true
color: '#8fc73e'
description: 'TeenTix Seattle events calendar'
descriptionFieldHandle: '0'
fieldLayout:
  tabs:
    -
      elementCondition: null
      elements:
        -
          elementCondition: null
          type: craft\fieldlayoutelements\HorizontalRule
          uid: 84806e1a-a393-4fdc-ac68-87324e655ffe
          userCondition: null
        -
          elementCondition: null
          fieldUid: d8797704-1354-4bc2-8ac7-4675305c5fcc # Event Dates Label
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 41e926a5-60b7-474d-9fe8-440f935c65e8
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 0968ba9e-9a4c-4238-a65b-ad3a323f8cca # Event Partner
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 1fc478a4-48ce-40a2-9624-1bdee6383950
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: b0a408b3-9d0d-409e-b9a9-564c0ecb283c # Venue
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: e8732ab7-17ae-4fcd-bead-18c8bb9b656d
          userCondition: null
          warning: null
          width: 100
      name: Dates
      uid: f4e77643-201b-492d-b0c7-0560a130925c
      userCondition: null
    -
      elementCondition: null
      elements:
        -
          elementCondition: null
          type: craft\fieldlayoutelements\HorizontalRule
          uid: d84d86e9-873d-4061-bde5-3f3361e689a7
          userCondition: null
        -
          elementCondition: null
          fieldUid: edd758f8-e0ec-4ef3-86af-51690335ece7 # Event Genre
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 5921eb2e-1122-4973-bef5-339c5975b328
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 9e9abb47-ea9a-4f12-96b5-d915fab1218f # Event Category
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: c40759bf-16c2-4413-8e8b-7fa5197acea7
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 7a51aca1-1a70-435b-bc16-6ec7bd2c4be0 # Featured Video Embed Code
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: ede5d05d-b491-48f2-9ab9-e48ac00a776a
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 1982700e-6aa7-4022-bc0f-ee96d891149c # Event Image Gallery
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: f6975382-5d0a-4b74-b295-d4c6e38f90b7
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 5764896d-54f2-425b-b36e-4278f5440071 # Body
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 2f0e4698-68cb-4638-9a3a-5474c009a1b9
          userCondition: null
          warning: null
          width: 100
      name: 'General Info'
      uid: c2ecde7a-a29c-47cf-8b8c-8d1277c9a74c
      userCondition: null
    -
      elementCondition: null
      elements:
        -
          elementCondition: null
          type: craft\fieldlayoutelements\HorizontalRule
          uid: 6efab980-781b-4d2d-a73b-c01540fdc869
          userCondition: null
        -
          elementCondition: null
          fieldUid: 2c7a7ae3-7151-45b4-a96c-7dc160f4cbdc # Website
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 8a27fef6-65ab-473a-a3b2-d95d1eb9585e
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 8065e96a-f788-4d62-bfab-88e8a9ec7872 # Social Links
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: d47ffc18-e560-43c0-89bd-f19b53952974
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 730d3ebd-b810-43f9-8762-02f4e5f2642b # Age Recommendations
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: e0d11720-ed57-4126-90c4-f88bbe15f76b
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: 63e026f8-a9fa-4d9d-8bce-ae031666a224 # Guest Ticket Price (Low)
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 2fe3f6d2-6943-4693-82e8-8277a018a681
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: f15b2626-a689-40e2-ac33-e96a23e3b391 # Guest Ticket Price (High)
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 5a0521b5-a0c9-4801-81ca-782565d86ac9
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: dd61bfae-367e-406a-8a90-69eac20f74d1 # Ticket Info
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: d4fb7145-09f6-4b8c-92f9-fb346f478a05
          userCondition: null
          warning: null
          width: 100
        -
          elementCondition: null
          fieldUid: b66ab360-21e0-4037-9f78-eff3d16eeccc # Ticket Availability
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: ed053dbb-ce5a-4819-b9b0-e4b3af0a6bcc
          userCondition: null
          warning: null
          width: 100
        -
          dismissible: false
          elementCondition: null
          style: warning
          tip: '***Important:*** By default, the the Box Office Info for the event is pulled from the associated partner(s). By filling this out, you will _override_ that content on the event page. Only complete this if the information is _truly_ specific to the event; otherwise, prefer updating the partner''s Box Office Info.'
          type: craft\fieldlayoutelements\Tip
          uid: 58ca488c-85e4-4bc0-905f-6c4f26d2671c
          userCondition: null
        -
          elementCondition: null
          fieldUid: 276f46bb-020c-42ad-8bc0-2b9f6e46f1dc # Box Office Info
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: 40ea7e39-6d43-4bac-abb5-6017a24b5333
          userCondition: null
          warning: null
          width: 100
      name: 'Additional Info'
      uid: b5000513-bba9-4b1b-aa9a-9c212e42cd7c
      userCondition: null
    -
      elementCondition: null
      elements:
        -
          dismissible: false
          elementCondition: null
          style: tip
          tip: "## SINGLE DAY EVENTS\r\nEnter the start day and time of the event. Set the end date to the same day and the calendar will automatically  select an end time that is one hour later. **The calendar does not display the end time.**\r\nIf the event is open all day that the venue is open  (for example, art exhibits), set the event to **All Day**.\r\n\r\n## MULTIPLE DAY EVENTS\r\nIf the event is running for multiple days, enter the first date and start time the for the event. The calendar will automatically select an end time that is one hour later. Do not change this. Then select **Repeats**. You will be given a few options to display repeating events. This creates a repeat rule for this particular start time. \r\n\r\nIf the event has multiple start times (for example: 4pm showing and 7pm showing or weekends at 7pm with a sunday matinee) you will need to add the additional start times as a separate entry under \"Calendar: Events Additional Time\".\r\n\r\n**Repeat - Select Dates**\r\nIn most cases, it will be best to use the select dates option. Select the dates from the calendar with the same start time as this event. **Do not add the first date of the event, you only need to add additional dates.**\r\n\r\n**Repeat - Days**\r\nIf the event is running for multiple days, you can select this option and set an end repeat date. To end the repeat, select **After** and set the date to the last day of the event. This is a good option for long running festivals.\r\n\r\n**Repeat - Weeks**\r\nIf the event is running on select days of the week, you can select this option, select the days of the week, and set an end repeat date. To end the repeat, select **After** and set the date to the last day of the event. This is a good option for museums, or events that only happen on a specific day of the week.\r\n\r\n**Repeat - Months**\r\nIf the event is running on select days of the month (first Thursday, etc), you can select this option, select **On the: first, second, third, fourth, last**, and set an end repeat date. To end the repeat, select **After** and set the date to the last day of the event. This is a good option for monthly events.\r\n\r\n**Repeat - Years**\r\nThis option is for events that happen annually and will probably never be selected.\r\n\r\n## SPECIAL CASES\r\n\r\n**Movies**\r\nFor movies with multiple screenings, enter the event as **All Day** and include a message in the description field to check with the venue website for movie times. \r\n\r\n"
          type: craft\fieldlayoutelements\Tip
          uid: 634632ae-1821-4906-94b9-7f40bc9b474e
          userCondition: null
        -
          elementCondition: null
          fieldUid: d3ed089c-46e6-4f89-b0ff-ab09fd25b395 # Old ID
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          uid: edd04d06-31dc-459c-a026-9a988691b151
          userCondition: null
          warning: null
          width: 100
      name: Help
      uid: f4b994a2-7a1e-45e0-a8b7-ce29041aadb7
      userCondition: null
  uid: 81732632-0eaf-4389-bcc8-9f8096034e43
handle: events
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: '0'
name: Events
siteSettings:
  cbaeaccc-5999-47b8-a4a6-5d9242b949a5:
    enabledByDefault: true
    hasUrls: true
    siteId: 0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0 # TeenTix
    template: calendar/event
    uriFormat: 'calendar/event/{slug}'
titleFormat: ''
titleLabel: Title
titleTranslationKeyFormat: ''
titleTranslationMethod: site
