# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "production-teentix-mysql"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[mount]
  source = "production_teentix_mysql2"
  destination = "/data"
  snapshot_retention = 30

[env]
  MYSQL_DATABASE = "teentix_prod"
  MYSQL_USER = "teentixadmin"

[build]
  image = "mysql:8.0"

[experimental]
  cmd = ["--datadir=/data/mysql", "--max-execution-time=15000"]
