tabs:
  -
    elements:
      -
        fieldUid: 2c0a312d-bf97-4a8c-97d0-76a9a06c1224 # Site
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1574d689-d01e-490f-aeda-ed36cd8e6193
        warning: null
        width: 100
      -
        fieldUid: a4ca1c2b-8c30-4901-ad55-36c919a81780 # Birthdate
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 8956220b-b1dc-459f-ae53-0d99aa6d4042
        warning: null
        width: 100
      -
        fieldUid: 29c55f0e-cfa5-4ec7-b754-12e37e503556 # Interests
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e842f676-4dbe-4892-bdc7-20bb14cb2091
        warning: null
        width: 100
      -
        fieldUid: 8f66492e-a2f2-4afb-8669-162d920a6eab # School
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7fea7fce-308e-47a1-9a0c-a975e72408bd
        warning: null
        width: 100
      -
        fieldUid: 44d08827-6c92-45d4-ad1a-7d0b1f090784 # Phone Number
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f9a7909b-9db4-4852-ab30-69f45a343ede
        warning: null
        width: 100
      -
        fieldUid: 12c1a7a7-5cae-4d47-8ef0-2b19f588e3ca # Applicant Type
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2b42d64a-0d9b-4205-b23a-83b5aa32b4ed
        warning: null
        width: 100
      -
        fieldUid: cbdb02eb-d774-4820-a58c-edda9dbbfb87 # Adult Name
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 52f0a1f4-eeed-4eb8-89e8-fab577043388
        warning: null
        width: 100
      -
        fieldUid: 35d67051-9b34-4eea-8ba8-182e395d2db3 # Adult Email Address
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c27514d6-c492-49d0-a3ff-b679d0bc3815
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 933cc760-9909-41d6-ab00-8b49de9ca7ab # Adult's Relationship to Teen
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: ea35cc9a-5e81-4256-9746-3073d38a4359
        userCondition: null
        warning: null
        width: 100
      -
        fieldUid: 10f190a7-a48f-4f72-8bdf-712778bbab43 # Hear About
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c5ed1cbb-8ccc-4bb0-8c8c-c90c389ddb68
        warning: null
        width: 100
      -
        fieldUid: 66e1d821-77cd-4b98-a3a3-0247e0919dfc # Referred
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 5a173f7c-6717-41e1-aec3-8b1bc372d559
        warning: null
        width: 100
      -
        fieldUid: be842f67-78b6-48de-ba9d-a590fff7fe7f # Newsletter Subscribe
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 07048484-a2e4-4c6e-96c7-fe4df8023c0d
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 5e8c93a1-7ae1-4c87-8da0-19115c2b9dcb # Provisional Member?
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f387bcd0-622e-43ed-91af-d08fa7e12df5
        userCondition: null
        warning: null
        width: 100
    name: Users
    sortOrder: 1
    uid: 12c711e3-36e5-45db-92b2-892232a75f6c
  -
    elements:
      -
        fieldUid: 1e632a7e-98f9-4ce4-9107-7dcfa2206b05 # City
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 30f7a151-59c3-4f15-b5a9-c4a5c4fe13b1
        warning: null
        width: 100
      -
        fieldUid: 360c03bd-6893-4b6d-971f-63a5c35094da # State
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: cb785ee4-de8c-4116-bd63-b393a96a5be2
        warning: null
        width: 100
      -
        fieldUid: 37a45800-9fce-4a5e-8cf5-9d1bbfc010e8 # Zip Code
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 97b635f8-abe6-463b-87e6-04939e3c1a6a
        warning: null
        width: 100
      -
        fieldUid: 40b2a3eb-57c5-41cc-864b-aec73e349cc8 # Country
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: d9c91907-3ed0-4a1a-a542-4336efde05f1
        warning: null
        width: 100
      -
        fieldUid: 70621ff5-3921-4cb4-a203-877963ba9751 # Demographic Ethnicity
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6d7d662b-42a8-4dfc-8416-e704164aa0e6
        warning: null
        width: 100
      -
        fieldUid: 1b6dddcc-94bf-431b-91e4-b27eaa0ff5fd # Demographic Language
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 188eac65-1800-457a-8438-8bdcd2dce390
        warning: null
        width: 100
      -
        fieldUid: 16480e16-bc67-413c-83f9-e824dc7db014 # Demographic Language Other
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f0a0dbab-11e4-46f0-95c3-965213b5d4c9
        warning: null
        width: 100
      -
        fieldUid: 7dd75f09-6042-4575-8cd9-107ad9cca4e5 # Demographic LGBTQ
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0f26c47b-d19e-4eb2-9cb8-76d0b83cd806
        warning: null
        width: 100
      -
        fieldUid: fe46e9dc-3387-4342-b45f-dcf02e0e59fe # Demographic Gender
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 9c751700-72dc-4c3c-bb2a-e5bfc7262c44
        warning: null
        width: 100
      -
        fieldUid: 6208178f-75ad-49a8-941a-81f98ab612fc # Demographic Gender Other
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: bdde24ab-422e-425e-b55f-3cba4cb768fc
        warning: null
        width: 100
      -
        fieldUid: ed2c25c5-46ce-4e73-ae55-a8a67a803da7 # Free and Reduced Meal Program Eligible
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b39bfeeb-bb34-49bb-a0e4-9f44c8db0857
        warning: null
        width: 100
    name: Demographic
    sortOrder: 2
    uid: e8c656a2-9d6c-457c-9284-8573bbca9f58
