columnSuffix: cuprfmlz
contentColumnType: text
fieldGroup: 4f2d0446-809a-4896-9a97-3b5409c32324 # Global
handle: calendarDonationPrompt
instructions: 'This text will appear on the calendar page, as is intended to be more targeted messaging for encouraging adults who use to calendar to support TeenTix.'
name: 'Calendar Donation Prompt'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 9eceeb25-5e29-4263-84f0-53203f894c30 # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
