columnSuffix: kubgdjti
contentColumnType: text
fieldGroup: 4f2d0446-809a-4896-9a97-3b5409c32324 # Global
handle: eventTicketPriceMember
instructions: 'If the Guest Ticket Price for an event is more than $5, this text is provided in order to reinforce the value of TeenTix Membership and to provide Members with expectations of what price they can expect.'
name: 'Member Ticket Price'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 9eceeb25-5e29-4263-84f0-53203f894c30 # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
