contentColumnType: string
fieldGroup: 77d77e0d-cbd3-4972-b03e-ec05812e4b1b # Event
handle: eventSocialLinks
instructions: ''
name: 'Social Links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_eventsociallinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
