contentColumnType: text
fieldGroup: 77d77e0d-cbd3-4972-b03e-ec05812e4b1b # Event
handle: eventTicketAvailability
instructions: ''
name: 'Ticket Availability'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 9eceeb25-5e29-4263-84f0-53203f894c30 # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
