columnSuffix: zzfckfir
contentColumnType: string
fieldGroup: 4f2d0446-809a-4896-9a97-3b5409c32324 # Global
handle: givebutterAccount
instructions: ''
name: 'Account #'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: true
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
