contentColumnType: string
fieldGroup: c4c09c27-bb9f-4773-90b5-120485d28e72 # Pass Usage
handle: mobilepartnerscannerplatform
instructions: 'Mobile partner scanning application platform used.'
name: MobilePartnerScannerPlatform
searchable: false
settings:
  byteLimit: null
  charLimit: '64'
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
