columnSuffix: znpycdje
contentColumnType: text
fieldGroup: 4f2d0446-809a-4896-9a97-3b5409c32324 # Global
handle: noticeProvisionalExpired
instructions: 'Display at the top of the site if the logged-in user is a Provisional Member, and their Membership has expired. '
name: 'Provisional Notice (Expired)'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 37036a58-d782-4f1e-b28d-d76b77295540 # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
