contentColumnType: string
fieldGroup: 61cb854e-4648-46e6-aa10-5c8caea1d4fe # Partners
handle: partnerType
instructions: ''
name: 'Partner Type'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Arts Partner'
        -
          - value
          - arts
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Community Partner'
        -
          - value
          - community
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
