contentColumnType: string
fieldGroup: e823674a-d2fc-4023-89dd-2bfacf7bc359 # Common
handle: relatedEvent
instructions: ''
name: 'Related Event'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'calendar:1'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: Solspace\Calendar\FieldTypes\EventFieldType
