contentColumnType: text
fieldGroup: e823674a-d2fc-4023-89dd-2bfacf7bc359 # Common
handle: subhead
instructions: ''
name: Subhead
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 9eceeb25-5e29-4263-84f0-53203f894c30 # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
