contentColumnType: string
fieldGroup: c4c09c27-bb9f-4773-90b5-120485d28e72 # Pass Usage
handle: teenhascompanion
instructions: 'Indicates whether or not the teen attended the show by themselves or with other people (e.g. teenagers, parents, other adults, etc).'
name: TeenHasCompanion
searchable: false
settings:
  byteLimit: null
  charLimit: '16'
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
