contentColumnType: text
fieldGroup: b69e2fb5-5a87-434a-9359-8986f38bc9cd # Notifications
handle: textBody
instructions: ''
name: 'Plain Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '6'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
