contentColumnType: string
fieldGroup: 1ea0247b-17e7-419a-8029-d57f032f4ed0 # Users
handle: userAdultEmailAddress
instructions: ''
name: 'Adult Email Address'
searchable: true
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
