contentColumnType: boolean
fieldGroup: 1ea0247b-17e7-419a-8029-d57f032f4ed0 # Users
handle: userFreeReducedEligible
instructions: ''
name: 'Free and Reduced Meal Program Eligible'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
