contentColumnType: text
fieldGroup: 1ea0247b-17e7-419a-8029-d57f032f4ed0 # Users
handle: userSite
instructions: ''
name: Site
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
