contentColumnType: datetime
fieldGroup: 1ea0247b-17e7-419a-8029-d57f032f4ed0 # Users
handle: userBirthdate
instructions: ''
name: Birthdate
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
