columnSuffix: null
contentColumnType: text
fieldGroup: a51ba621-81f3-4260-a89b-f7dc5e425ee4 # Emails
handle: welcomeEmailHtml
instructions: 'Welcome email text for html email clients'
name: 'Welcome Email (HTML)'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 37036a58-d782-4f1e-b28d-d76b77295540 # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
