dateModified: 1713803018
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft Project'
  replyToEmail: null
  template: ''
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    1c4db2bd-b409-4bf2-a56e-c3327f0b160e: 'Craft Project' # Craft Project
    283a253c-a365-4823-89c4-b48fbd2232a3: 'Craft Project' # Craft Project
system:
  edition: pro
  live: true
  name: 'Craft Project'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
