dateModified: 1706551588
email:
  fromEmail: tim@craftcms.com
  fromName: 'Craft 5 Project'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7ce3d083-e1fc-4590-99ea-3823abbbd702: 'Craft 5 Project' # Craft 5 Project
    eb0a0fd2-aaf3-4dd4-99e6-457fd92acefe: 'Craft 5 Project' # Craft 5 Project
system:
  edition: solo
  live: true
  name: 'Craft 5 Project'
  schemaVersion: 5.0.0.16
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
