enableVersioning: true
handle: la_pages
name: 'LA Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7d81a2c3-37f0-4c8e-ae20-7d3ab5055184: # TeenTix LA
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: f6b793a8-6354-450b-8e6a-c1a31ef69f6a
type: structure
