defaultPlacement: end
enableVersioning: true
handle: mySection
name: 'My Section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1c4db2bd-b409-4bf2-a56e-c3327f0b160e: # Craft Project
    enabledByDefault: true
    hasUrls: true
    template: my-section/_entry
    uriFormat: 'my-section/{slug}'
type: channel
