enableVersioning: true
handle: pages
name: 'SEA Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: cd63c657-073a-4dc1-bcda-bfdfe1426b53
type: structure
