enableVersioning: true
handle: partners
name: 'SEA Partners'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    enabledByDefault: true
    hasUrls: true
    template: partners/_entry
    uriFormat: 'partners/{slug}'
type: channel
