enableVersioning: true
handle: passUsage
name: 'SEA Pass Usage'
propagationMethod: all
siteSettings:
  0e7592e9-74d0-48f7-a1d7-2bf18b97d6a0: # TeenTix
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
