[
"None",
"Homeschool",
"Miller Junior High",
"J M Weatherwax High School",
"Harbor High School",
"Grays Harbor Juvenile Detention",
"Hoquiam Middle School",
"Hoquiam High School",
"North Beach Senior High School",
"North Beach Junior High School",
"Mccleary Elem",
"Montesano Jr-Sr High",
"East Grays Harbor High School",
"Elma High School",
"Elma Middle School",
"Taholah High School",
"Lake Quinault School",
"Wishkah Valley Elementary/High School",
"Ocosta Junior - Senior High",
"Oakville High School",
"Homeconnection",
"Oak Harbor High School",
"North Whidbey Middle School",
"Coupeville High School",
"Coupeville Middle School",
"South Whidbey Academy",
"South Whidbey Middle",
"South Whidbey High School",
"Queets-Clearwater Elementary",
"Brinnon Elementary",
"PI Program",
"Chimacum High School",
"Chimacum Middle School",
"OCEAN",
"Port Townsend High School",
"Blue Heron Middle School",
"Middle College High School",
"Tops K-8 School",
"Seattle World School",
"Pathfinder K-8 School",
"Interagency Programs",
"Cascade Parent Partnership Program",
"Salmon Bay K-8 School",
"The Center School",
"Madrona K-5 School",
"Franklin High School",
"Broadview-Thomson K-8 School",
"Ballard High School",
"West Seattle High School",
"Roosevelt High School",
"Garfield High School",
"Hamilton International Middle School",
"Cleveland High School STEM",
"Madison Middle School",
"Eckstein Middle School",
"Catharine Blaine K-8 School",
"David T. Denny International Middle School",
"Mercer International Middle School",
"Chief Sealth International High School",
"Ingraham High School",
"Whitman Middle School",
"Rainier Beach High School",
"Nathan Hale High School",
"McClure Middle School",
"Aki Kurose Middle School",
"South Lake High School",
"Nova High School",
"Licton Springs K-8",
"Washington Middle School",
"Orca K-8 School",
"South Shore PK-8 School",
"Federal Way Public Academy",
"Federal Way High School",
"Woodmont K-8 School",
"Lakota Middle School",
"Totem Middle School",
"Thomas Jefferson High School",
"Sacajawea Middle School",
"Kilo Middle School",
"Decatur High School",
"Illahee Middle School",
"Othello High School",
"McFarland Middle School",
"Lind-Ritzville High School",
"Ritzville High School",
"Ritzville Grade School",
"Educational Opportunity Center",
"Charles Francis Adams High School",
"Lincoln Middle School",
"Asotin Jr Sr High",
"Legacy High School",
"Kennewick High School",
"Highlands Middle School",
"Park Middle School",
"Kamiakin High School",
"Benton/Franklin Juvenile Justice Center",
"Desert Hills Middle School",
"Tri-Tech Skills Center",
"Horse Heaven Hills Middle School",
"Southridge High School",
"Paterson Elementary School",
"Kiona-Benton City High School",
"Kiona-Benton City Middle School",
"River View High School",
"Finley Middle School",
"Prosser High School",
"Housel Middle School",
"Carmichael Middle School",
"Chief Joseph Middle School",
"Twin Rivers Group Home",
"Richland High School",
"Hanford High School",
"Enterprise Middle School",
"Rivers Edge High School",
"Manson High School",
"Stehekin Elementary",
"Entiat Middle and High School",
"Chelan Middle School",
"Holden Village Community School",
"Chelan High School",
"CASHMERE MIDDLE SCHOOL",
"CASHMERE HIGH SCHOOL",
"Cascade High School",
"Icicle River Middle School",
"Skill Source",
"Westside High School",
"Valley Academy Of Learning",
"Chelan County Juvenile Detention Center",
"Wenatchee High School",
"Pioneer Middle School",
"Castlerock Early Learning Center",
"Orchard Middle School",
"Foothills Middle School",
"Parents As Partners",
"Port Angeles High School",
"Clallam Co Juvenile Detention",
"Stevens Middle School",
"Lincoln High School",
"Crescent School",
"Sequim Senior High",
"Sequim Middle School",
"Neah Bay Junior/ Senior High School",
"Clallam Bay High & Elementary",
"Forks Alternative School",
"District Run Home School",
"Forks Junior-Senior High School",
"Fir Grove Childrens Center",
"Vancouver School of Arts and Academics",
"Gate Program",
"Fort Vancouver High School",
"Hudson's Bay High School",
"Mcloughlin Middle School",
"Columbia River High",
"Jason Lee Middle School",
"Washington State School for the Blind",
"Gaiser Middle School",
"Lewis and Clark High School",
"Alki Middle School",
"Discovery Middle School",
"Skyview High School",
"Hockinson Middle School",
"Hockinson High School",
"La Center Middle School",
"La Center High School",
"Green Mountain School",
"Washougal High School",
"Jemtegaard Middle School",
"Canyon Creek Middle School",
"49th Street Academy",
"Evergreen High School",
"Riverpoint Academy",
"Westwood Middle School",
"Vancouver iTech Preparatory",
"Brewster Alternative School",
"Columbia Basin Technical Skills Center",
"iGrad",
"Louisa Boren STEM K-8",
"Southwest Youth and Family Services",
"Spokane Valley Tech",
"Columbia Alternative School",
"Talley High School",
"Gateway",
"Manson Middle School",
"Mabton Jr. Sr. High",
"Clark County Juvenile Detention School",
"Maple Grove K-8",
"Lind-Ritzville Middle School",
"Snoqualmie Parent Partnership Program",
"Transition Day Students",
"Oakridge Group Home",
"CVA-Lopez Island",
"Mt. Rainier Parent Partnership",
"The Community School",
"Washington Youth Academy",
"Lind Ritzville Middle School",
"GRAVITY High School",
"Open Doors at LWIT",
"Fresh Start",
"Henrietta Lacks Health and Bioscience High School",
"Discovery High School",
"Youthsource",
"Open Doors Re-Engagement Wenatchee",
"Lewis County Jail",
"Chief Kitsap Academy",
"Puyallup Open Doors/POD",
"Puyallup Parent Partnership Program",
"Skill Source Learning Center",
"Grad Alliance Program",
"La Center Home School Academy",
"CVSD Open Doors Programs",
"Open Doors Youth Reengagement Sultan",
"Everett Reengagement Academy",
"Northshore Online School",
"New Beginnings",
"Selah Academy Reengagement Program",
"Open Door Youth Reengagement Renton",
"Lake Roosevelt Alternative School",
"SE Area Technical Skills Center",
"White River Reengagement Program",
"PRIDE Prep School",
"Bellingham Re-Engagement Program",
"Open Doors Vancouver",
"iGrad Academy",
"Open Doors Youth Re-Engagement Spokane",
"East Valley Middle School",
"Open Doors Youth Reengagement (1418)",
"Granite Falls Open Doors",
"Jane Addams Middle School",
"SHS Graduation Alliance",
"CHS Drop-Out Reengagement Program",
"Endeavor Middle School",
"Yakima Open Doors",
"re-engagement",
"Edmonds Career Access Program",
"Futurus High School",
"Open Doors Battle Ground",
"Spokane Public Montessori",
"College Place High School",
"Bellingham Family Partnership Program",
"Desert Oasis High School",
"Lewis County Alternative School",
"Highline Open Doors 1418",
"Highline Home School Center",
"Acceleration Academy",
"Lummi Nation School",
"Svsd Open Doors",
"Summit Public School: Sierra",
"Summit Public School: Olympus",
"Excel Public Charter School",
"Destiny Middle School",
"SOAR Academy Public Charter School",
"Rainier Prep",
"Selah Middle School",
"White River Homeschool",
"Internet Pasco Academy of Learning",
"Career & Academic Re-engagement Center",
"Cheney Open Doors",
"ESD 112 Open Doors Reengagement",
"Step Up to College Open Doors High School",
"Discovery High School-Achieve",
"Mead Open Doors",
"Marysville NWESD 189 Youth Engagement",
"Ugrad â€“ ESD123 Re-Engagement Program",
"Interagency Open Doors",
"Woodland Middle School",
"Futures Program",
"CPSD Open Doors Program",
"Open Den",
"Open Doors Reengagement Program",
"Lakewood NWESD 189 Open Door Program",
"Educational Opportunity Center Reengagement",
"Other Schools",
"Mossyrock Academy",
"East Grays Harbor Open Doors",
"Re-Engagement School (Nine Mile Falls)",
"Cascade Home-Link",
"Quileute Tribal School",
"Bates Technical College - Open Doors",
"EV Online",
"EV Parent Partnership",
"NEWESD 101 Open Doors",
"Open Doors Evergreen",
"Gibson Ek High School",
"Chinook Middle School",
"The Outreach Program",
"Outcomes for Academic Resilience",
"Mabton Step Up To College",
"Washington Connections Academy",
"Mary Walker Promise",
"Meridian Impact Re-Engagement",
"Mount Vernon Open Doors",
"Salish Middle School",
"Ocean Beach Alternative School",
"Connections Academy",
"Industrial Design Engineering and Art",
"Opportunity Youth Reengagement",
"Wellpinit Fort Simcoe SEA",
"Ferndale Re-engagement",
"Blaine Re-Engagement",
"IMPACT Reengagement Program",
"Rainier Valley Leadership Academy",
"Summit Public School: Atlas",
"Willow Public School",
"Barker Creek Community School",
"Covington Middle School",
"Cascade Middle School",
"Legacy High School",
"Wyeast Middle School",
"Mountain View High School",
"Cascadia Technical Academy Skills Center",
"Pacific Middle School",
"Frontier Middle School",
"Heritage High School",
"Shahala Middle School",
"Skyridge Middle School",
"Camas High School",
"CAM Academy",
"Homelink River",
"Battle Ground High School",
"Amboy Middle School",
"Laurin Middle School",
"Pleasant Valley Middle",
"Prairie High School",
"Summit View High School",
"Ridgefield High School",
"View Ridge Middle School",
"Dayton High School",
"Dayton Middle School",
"Starbuck School",
"R A Long High School",
"Monticello Middle School",
"Mark Morris High School",
"Cascade Middle School",
"Toutle Lake High School",
"Castle Rock High School",
"Castle Rock Middle School",
"Kalama Middle School",
"TEAM High School",
"Woodland High School",
"Kelso High School",
"Huntington Middle School",
"Cowlitz County Youth Services Center",
"Coweeman Middle School",
"Orondo Elementary and Middle School",
"Bridgeport High School",
"Bridgeport Middle School",
"Eastmont Senior High",
"Canyon View Group Home",
"Eastmont Junior High",
"Sterling School",
"Wenatchee Valley Technical Skills Center",
"Mansfield Elem and High School",
"Waterville High School",
"Curlew Elem & High School",
"Orient Elem",
"Inchelium High School",
"Inchelium Middle School",
"Republic Senior High School",
"Mcloughlin Middle School",
"Pasco Senior High School",
"Stevens Middle School",
"New Horizons High School",
"Ellen Ochoa Middle School",
"Palouse Junction High School",
"Robert L Olds Junior High School",
"Connell High School",
"Pomeroy Jr Sr High School",
"Sentinel Tech Alt School",
"Wahluke High School",
"Quincy Junior High",
"Quincy High School",
"Warden High School",
"Warden Middle School",
"Coulee City MS",
"Almira Coulee Hartline High School",
"Smokiam Alternative High School",
"Soap Lake Middle & High School",
"Royal High School",
"Royal Middle School",
"Frontier Middle School",
"Chief Moses Middle School",
"Moses Lake High School",
"Ephrata High School",
"Ephrata Middle School",
"Wilson Creek High",
"Lake Roosevelt Jr/Sr High School",
"TAFA at Saghalie",
"Ferndale Family Connections",
"Marysville Getchell High School",
"Pacific Crest Innovation Academy",
"North Creek High School",
"Risdon Middle School",
"Meany Middle School",
"Robert Eagle Staff Middle School",
"Leona Libby Middle School",
"Arlington Open Doors",
"Wa He Lut Indian School",
"Sage Hills Open Doors",
"Mukilteo Reengagement Academy Open Doors",
"CRCC-Open Doors",
"Open Doors - Youth Reengagement Program",
"DB Youth Services",
"Student Success Open Doors Academy",
"West Valley Virtual Academy 7-8",
"West Valley Virtual Academy 9-12",
"Grays Harbor Academy",
"Hood Canal Middle School",
"Auburn Opportunity Project",
"Chewelah Open Doors Reengagement Program",
"Open Doors",
"Steilacoom PRIDE Academy",
"Insight School of WA Open Doors Program",
"Ferry County Open Doors",
"Eatonville Online Academy",
"Camas School District Open Doors",
"Discovery High School",
"Odyssey Middle School",
"Cascadia Technical Academy ALE",
"Tukwila Online Learning",
"PSD U Grad Academy",
"Home Pride",
"West Valley Open Doors",
"Stem Academy at SVT",
"Kalama High School",
"Choice Academy",
"Kelso Goal Oriented Learning Design",
"Shelton Open Doors",
"Chief Leschi Schools",
"Yakama Nation School",
"Todd Beamer High School",
"Enumclaw Sr High School",
"Enumclaw Middle School",
"Thunder Mountain Middle School",
"Mercer Island High School",
"Islander Middle School",
"CHOICE Academy",
"Puget Sound Skills Center",
"Highline High School",
"Sylvester Middle School",
"Chinook Middle School",
"Evergreen High School",
"Cascade Middle School",
"Mount Rainier High School",
"Pacific Middle School",
"Tyee High School",
"Family Link",
"Vashon Island High School",
"McMurray Middle School",
"Griffin Home",
"H.O.M.E. Program",
"Renton Senior High School",
"McKnight Middle School",
"Dimmitt Middle School",
"Nelsen Middle School",
"Hazen Senior High School",
"Lindbergh Senior High School",
"Skykomish Elementary School",
"Skykomish High School",
"Bellevue High School",
"Highland Middle School",
"Sammamish Senior High",
"Tyee Middle School",
"Chinook Middle School",
"Tillicum Middle School",
"Newport Senior High School",
"Interlake Senior High School",
"Odle Middle School",
"Showalter Middle School",
"Foster Senior High School",
"CLIP",
"Cedarcrest High School",
"Tolt Middle School",
"Cascade Middle School",
"West Auburn Senior High School",
"Auburn Senior High School",
"Olympic Middle School",
"Rainier Middle School",
"Mt Baker Middle School",
"Auburn Riverside High School",
"Tahoma Senior High School",
"Summit Trail Middle School",
"Maple View Middle School",
"Two Rivers School",
"Mount Si High School",
"Chief Kanim Middle School",
"Issaquah Middle School",
"Issaquah High School",
"Echo Glen School",
"Maywood Middle School",
"Pine Lake Middle School",
"Liberty Sr High School",
"Beaver Lake Middle School",
"Skyline High School",
"Home Education Exchange",
"Fircrest Residential Habilitation",
"Shorecrest High School",
"Kellogg Middle School",
"Albert Einstein Middle School",
"Shorewood High School",
"Emerson K-12",
"International Community School",
"Environmental & Adventure School",
"Futures School",
"Kirkland Middle School",
"Lake Washington High",
"Redmond Middle School",
"Redmond High",
"Finn Hill Middle School",
"Rose Hill Middle School",
"Juanita High",
"Emerson High School",
"Kamiakin Middle School",
"Evergreen Middle School",
"Northstar Middle School",
"Inglewood Middle School",
"Eastlake High School",
"Regional Justice Center",
"Kent-Meridian High School",
"Kent Mountain View Academy",
"Meridian Middle School",
"Kentridge High School",
"Meeker Middle School",
"Mattson Middle School",
"Kentwood High School",
"Cedar Heights Middle School",
"Northwood Middle School",
"Kentlake High School",
"Northshore Networks",
"Bothell High School",
"Kenmore Middle School",
"Woodinville Community Center",
"Inglemoor HS",
"Canyon Park Middle School",
"Leota Middle School",
"Secondary Academy for Success",
"Northshore Middle School",
"Woodinville HS",
"Skyview Middle School",
"Timbercrest Middle School",
"Renaissance Alternative High School",
"Bremerton Home Link Program",
"West Hills S.T.E.M. Academy",
"Bremerton High School",
"Morgan Center School",
"West Sound Technical Skills Center",
"Mountain View Middle School",
"Odyssey Multiage Program",
"Mosaic Home Education Partnership",
"Bainbridge High School",
"Woodward Middle School",
"Pal Program",
"Poulsbo Middle School",
"Middle School Options",
"North Kitsap High School",
"Kingston Middle School",
"Central Kitsap High School",
"Central Kitsap Middle School",
"Fairview Middle School",
"Olympic High School",
"Ridgetop Middle School",
"Klahowya Secondary",
"Explorer Academy",
"South Kitsap High School",
"Marcus Whitman Middle School",
"Kitsap Co Detention Ctr",
"Cedar Heights Middle School",
"Discovery",
"John Sedgwick Middle School",
"Easton School",
"Thorp Elem & Jr Sr High",
"Morgan Middle School",
"Ellensburg High School",
"Kittitas High School",
"Parke Creek Treatment Ctr",
"Cle Elum Roslyn High School",
"Walter Strom Middle School",
"Bickleton Elementary & High Schl",
"Centerville Elementary",
"Trout Lake School",
"Glenwood Secondary",
"Klickitat Elem & High",
"Goldendale High School",
"Goldendale Middle School",
"Columbia High School",
"Wayne M Henkle Middle School",
"Lyle High School",
"Lyle Middle School",
"Napavine Jr Sr High School",
"Mossyrock Jr./Sr. High School",
"Morton Junior-Senior High",
"Adna Middle/High School",
"Winolequa Learning Academy",
"Winlock Senior High",
"Winlock Middle School",
"Boistfort Elem",
"Toledo High School",
"Toledo Middle School",
"Onalaska High School",
"Onalaska Elementary School",
"Onalaska Middle School",
"Lewis County Juvenile Detention",
"Green Hill Academic School",
"W F West High School",
"Chehalis Middle School",
"White Pass Jr. Sr. High School",
"Centralia High School",
"Centralia Middle School",
"Sprague High School",
"Reardan Middle-Senior High School",
"Almira Elementary School",
"Creston Jr-Sr High School",
"Odessa High School",
"Wilbur Secondary School",
"Harrington High School",
"Davenport Senior High School",
"Southside Elementary",
"Grapeview Elementary & Middle School",
"Mason County Detention Center",
"Shelton High School",
"Choice Middle and High School",
"Oakland Bay Junior High School",
"Pioneer Middle School",
"James A. Taylor High School",
"North Mason Homelink Program",
"Hawkins Middle School",
"North Mason Senior High School",
"Hood Canal Elementary School",
"Nespelem Elementary",
"Omak High School",
"Omak Middle School",
"Paschal Sherman",
"Highlands High School",
"Okanogan Middle School",
"Okanogan High School",
"Okanogan Co Juvenile Detention",
"Brewster High School",
"Brewster Middle School",
"Pateros High School",
"Alternative School",
"Home School Experience",
"Liberty Bell Jr Sr High",
"Tonasket High School",
"Tonasket Middle School",
"Oroville Middle-High School",
"Hilltop School",
"Ilwaco High School",
"Raymond Jr Sr High School",
"South Bend High School",
"Naselle Jr Sr High Schools",
"Naselle Youth Camp School",
"Willapa Valley Middle-High",
"Newport High School",
"Sadie Halstead Middle School",
"Cusick Jr Sr High School",
"Pioneer Middle",
"Steilacoom High",
"Puyallup Online Academy/POA",
"Puyallup High School",
"Edgemont Jr High",
"Kalles Junior High",
"Aylen Jr High",
"Rogers High School",
"Ballou Jr High",
"Walker High School",
"Ferrucci Jr High",
"Stahl Junior High",
"Emerald Ridge High School",
"Alternative Spcl Needs Div Occ",
"Comm Based Trans Program",
"Day Reporting School",
"TCC Fresh Start",
"Tacoma School of the Arts",
"Remann Hall Juvenile Detention Center",
"Stadium",
"Lincoln",
"Jason Lee",
"Stewart",
"Mason",
"Gray",
"Baker",
"Meeker",
"Wilson",
"Bryant",
"Mt Tahoma",
"Truman",
"Foss",
"Oakland High School",
"Pearl Street Center",
"Carbonado Historical School 19",
"Curtis Junior High",
"Narrows View Intermediate",
"Curtis Senior High",
"Drum Intermediate",
"Sumner High School",
"Sumner Middle School",
"Lakeridge Middle School",
"Mountain View Middle School",
"North Tapps Middle School",
"Orting High School",
"Orting Middle School",
"Alfaretta House",
"Re-Entry High School",
"Re-Entry Middle School",
"Firwood",
"Clover Park High School",
"Hudtloff Middle School",
"Mann Middle School",
"Lakes High School",
"Woodbrook Middle School",
"Lochburn Middle School",
"Henderson Bay Alt High School",
"Goodman Middle School",
"Peninsula High School",
"Gig Harbor High",
"Key Peninsula Middle School",
"Kopachuck Middle School",
"Harbor Ridge Middle School",
"Franklin Pierce High School",
"Morris Ford Middle School",
"Perry G Keithley Middle School",
"Washington High School",
"Gates Secondary School",
"Challenger High School",
"Bethel High School",
"Bethel Middle School",
"Spanaway Middle School",
"Spanaway Lake High School",
"Cedarcrest Middle School",
"Frontier Middle School",
"Eatonville High School",
"Columbia Crest A-STEM Academy",
"Eatonville Middle School",
"Glacier Middle School",
"White River High School",
"Fife High School",
"Surprise Lake Middle School",
"Shaw Island Elementary School",
"OASIS K-12",
"Orcas Island High School",
"Waldron Island School",
"Orcas Island Middle School",
"Lopez Middle High School",
"Decatur Elementary",
"Friday Harbor High School",
"Friday Harbor Middle School",
"Twin Cedars High School",
"Concrete High School",
"Burlington Edison High School",
"Edison Elementary - Burlington/Edison",
"West View Elementary",
"Lucille Umbarger Elementary",
"Allen Elementary",
"Bay View Elementary",
"State Street High School",
"Sedro Woolley Senior High School",
"Cascade Middle School",
"Anacortes High School",
"Anacortes Middle School",
"La Conner High School",
"La Conner Middle",
"Conway School",
"Mount Vernon High School",
"Skagit County Detention Center",
"La Venture Middle School",
"Mount Vernon Special Ed",
"Mount Baker Middle School",
"Skamania Elementary",
"Mount Pleasant School",
"Mill A Elementary School",
"Stevenson High School",
"Wind River Middle School",
"NW Learning Center",
"Sno Co Jail",
"Pass Program",
"Everett High School",
"North Middle School",
"Snohomish Detention Center",
"Evergreen Middle School",
"Cascade High School",
"Eisenhower Middle School",
"Sequoia High School",
"Heatherwood Middle School",
"Gateway Middle School",
"Henry M. Jackson High School",
"Homelink",
"Lake Stevens Sr High School",
"Lake Stevens Middle School",
"North Lake Middle School",
"Prove High School",
"Olympic View Middle School",
"Mariner High School",
"Sno-Isle Skills Center",
"Explorer Middle School",
"ACES High School",
"Voyager Middle School",
"Harbour Pointe Middle School",
"Kamiak High School",
"Edmonds eLearning Academy",
"Unassigned School",
"Maplewood Parent Coop",
"Contracted Schools",
"Edmonds Woodway High School",
"Mountlake Terrace High School",
"Meadowdale Middle School",
"Madrona K-8 School",
"Meadowdale High School",
"Alderwood Middle School",
"Brier Terrace Middle School",
"College Place Middle School",
"Lynnwood High School",
"Scriber Lake High School",
"Stillaguamish Valley Learning Center",
"Arlington High School",
"Post Middle School",
"Weston High School",
"10th Street School",
"Heritage School",
"School Home Partnership Program",
"Totem Middle School",
"Marysville Middle School",
"Cedarcrest School",
"Index Elementary School",
"Out Of District Special Ed",
"Sky Valley Education Center",
"Leaders In Learning",
"Youth Re-Engagement",
"Monroe High School",
"Hidden River Middle School",
"Snohomish Center",
"Snohomish Online Learning",
"Snohomish High School",
"High School Re Entry",
"Valley View Middle School",
"AIM High School",
"Centennial Middle School",
"Lakewood Middle School",
"Lakewood High School",
"Sultan Middle School",
"Sultan Senior High School",
"Darrington High School",
"Granite Falls High School",
"Granite Falls Middle School",
"Lincoln Hill High School",
"Stanwood Middle School",
"Stanwood High School",
"Port Susan Middle School",
"A-3 Multiagency Adolescent Prog",
"Eagle Peak at Pratt",
"Daybreak Alternative School",
"Alternative Tamarack School",
"SCCP Images",
"The Healing Lodge",
"North Central High School",
"Lewis & Clark High School",
"Libby Center",
"Rogers High School",
"Shadle Park High School",
"Shaw Middle School",
"Glover Middle School",
"Sacajawea Middle School",
"Ferris High School",
"Salk Middle School",
"Garry Middle School",
"Excelsior Youth Center School",
"Spokane Area Professional-Technical Skills Center",
"Chase Middle School",
"Orchard Prairie Elementary",
"Lakeside High School",
"Lakeside Middle School",
"Medical Lake High School",
"Martin Hall Detention Ctr",
"Medical Lake Middle School",
"Mead Alternative High School",
"Mead Education Partnership Prog",
"Mead Senior High School",
"Mountainside Middle School",
"Northwood Middle School",
"Mt Spokane High School",
"North Pines Middle School",
"Central Valley High School",
"Bowdish Middle School",
"University High School",
"Summit School",
"Greenacres Middle School",
"Evergreen Middle School",
"Mica Peak High School",
"Horizon Middle School",
"Freeman High School",
"Three Springs High School",
"Cheney Middle School",
"Cheney High School",
"Continuous Curriculum School",
"East Valley High School",
"Liberty High School",
"Liberty Jr High & Elementary",
"Dishman Hills High School",
"West Valley City School",
"Spokane Valley High School",
"Spokane Valley Transition School",
"West Valley High School",
"Centennial Middle School",
"Deer Park Home Link Program",
"Deer Park Middle School",
"Deer Park High School",
"Riverside Middle School",
"Riverside High School",
"Onion Creek Elementary",
"Chewelah Alternative Educational Programs",
"Jenkins Junior/Senior High",
"Wellpinit Middle School",
"Valley School",
"Panorama School",
"Colville Senior High School",
"Colville Junior High School",
"Summit Valley School",
"Mary Walker Alternative High Schl",
"Springdale Academy",
"Mary Walker High School",
"Springdale Middle School",
"Northport Elementary School",
"Northport High School",
"Kettle Falls Middle School",
"Kettle Falls High School",
"Yelm Extension School",
"Yelm Middle School",
"Yelm High School 12",
"North Thurston High School",
"Chinook Middle School",
"Nisqually Middle School",
"Timberline High School",
"South Sound High School",
"Komachin Middle School",
"River Ridge High School",
"Secondary Options",
"Tumwater High School",
"Tumwater Middle School",
"Thurs Co Juv Det/Tumwater West E",
"New Market Skills Center",
"George Washington Bush Middle Sch",
"A G West Black Hills High School",
"Avanti High School",
"Olympia High School",
"Jefferson Middle School",
"Reeves Middle School",
"Washington Middle School",
"Capital High School",
"Thurgood Marshall Middle School",
"Rainier Middle School",
"Rainier Senior High School",
"Griffin School",
"H.e.a.r.t. High School",
"Rochester Middle School",
"Rochester High School",
"Tenino High School",
"Tenino Middle School",
"Julius A Wendt Elementary/John C Thomas Middle School",
"Wahkiakum High School",
"Alternative Education Program",
"Pioneer Middle School",
"Walla Walla County Juvenile Detention",
"Walla Walla High School",
"Garrison Middle School",
"Lincoln High School",
"John Sager Middle School",
"Touchet Elem & High School",
"Columbia Middle School",
"Columbia High School",
"Preston Hall Middle School",
"Waitsburg High School",
"Prescott Jr Sr High",
"Options High School",
"Visions (Seamar Youth Center)",
"Fairhaven Middle School",
"Whatcom Middle School",
"Bellingham High School",
"Shuksan Middle School",
"Whatcom Co Detention Center",
"Sehome High School",
"Kulshan Middle School",
"Squalicum High School",
"Ferndale High School",
"Vista Middle School",
"Horizon Middle School",
"Blaine High School",
"Blaine Middle School",
"Lynden Middle School",
"Lynden High School",
"Meridian High School",
"Meridian Middle School",
"Nooksack Valley High School",
"Nooksack Valley Middle School",
"Mount Baker Senior High",
"Mount Baker Junior High",
"Lacrosse Elementary School",
"Lacrosse High School",
"Lamont Middle School",
"Tekoa High School",
"Pullman High School",
"Lincoln Middle School",
"Leonard M Jennings Elementary",
"Colfax High School",
"Palouse High School",
"Garfield Middle School",
"Steptoe Elementary School",
"Endicott/St John Elem and Middle",
"St John/Endicott High",
"Oakesdale High School",
"Union Gap School",
"Naches Valley High School",
"Naches Valley Middle School",
"Davis High School",
"Washington Middle School",
"Franklin Middle School",
"Discovery Lab School",
"Eisenhower High School",
"Wilson Middle School",
"Lewis & Clark Middle School",
"Juvenile Detention Center",
"Stanton Academy",
"East Valley High School",
"East Valley Central Middle School",
"Selah High School",
"Selah Academy",
"Contract Learning Center",
"Grandview High School",
"Grandview Middle School",
"Sunnyside High School",
"Harrison Middle School",
"Computer Academy Toppenish High School",
"Toppenish Middle School",
"Toppenish High School",
"Highland Junior High School",
"Highland High School",
"Granger Middle School",
"Granger High School",
"Zillah High School",
"Zillah Middle School",
"Wapato Middle School",
"Wapato High School",
"Pace Alternative High School",
"West Valley High School",
"West Valley Jr High",
"West Valley Middle School",
"Mount Adams Middle School",
"White Swan High School",
"Loon Lake Homelink Program",
"Independent Scholar",
"Parent Partnership",
"Columbia Virtual Academy",
"Loowit High School",
"Eagle Harbor High School",
"Home Choice Academy",
"Trojan Alternative School",
"Olympic Middle School",
"Angelo Giaudrone Middle School",
"Burlington-Edison Alternative School",
"Marysville Mountain View Arts and Technology High School",
"Interagency Detention School",
"Spokane Juvenile Detention School",
"Structural Alt Confinement School",
"Bridgeport Aurora High School",
"Port Gardner",
"Columbia Junior High School",
"Student Link",
"Cougar Mountain Middle School",
"Chelan School of Innovation",
"Mid-Columbia Parent Partnership",
"Cascade K-8 Community School",
"Employment Transition Program",
"Quincy Innovation Academy",
"Republic Parent Partner",
"Palouse at Garfield Middle School",
"Garfield at Palouse High School",
"Jefferson Middle School",
"Griffin Bay School",
"Spokane Valley Learning Academy",
"Edmonds Heights K-12",
"Yakima Valley Technical Skills Center",
"International School",
"Raisbeck Aviation High School",
"Vancouver Home Connection",
"New Start",
"Freeman Middle School",
"Stella Schola",
"Republic Junior High",
"Okanogan Alternative High School",
"Lynden Academy",
"Muckleshoot Tribal School",
"Swiftwater Learning Center",
"Clovis Point",
"Skagit Academy",
"School to Life",
"Saratoga School",
"Haller Middle School",
"Garrett Heyns High School",
"New Market High School",
"Mill Creek Middle School",
"Blaine Home Connections",
"Bonney Lake High School",
"Mt. Solo Middle School",
"Harrison Prep School",
"Big Picture School",
"Sequoyah Middle School",
"HomeConnection",
"Taholah Elementary & Middle School",
"Graham Kapowsin High School",
"HomeWorks",
"Auburn Mountainview High School",
"Park Place Middle School",
"Medical Lake Endeavors",
"Meridian Parent Partnership Program",
"Sierra Vista Middle School",
"Ridgeline Middle School",
"Liberty Middle School",
"Renaissance School",
"Island Juvenile Detention Education Program",
"Bates Technical High School",
"Renton Academy",
"Insight School of Washington",
"Olympia Regional Learning Academy",
"White Salmon Academy",
"Crossroads Community School",
"Northwest Career and Technical High School",
"Kingston High School",
"Daybreak Middle",
"Kent Phoenix Academy",
"Cavelero Mid High School",
"Hayes Freedom High School",
"Lake Washington Technical Academy",
"Phoenix High School",
"Federal Way Running Start Home School",
"Lincoln Academy",
"Union High School",
"Mount Baker Academy",
"Sky Valley Options",
"Career Link",
"Pend Oreille River School",
"Glacier Peak High School",
"Tukes Valley Middle School",
"Chief Umtuch Middle",
"Twin Falls Middle School",
"Glacier View Junior High",
"Wahluke Junior High",
"Vancouver Virtual Learning Academy",
"Okanogan Outreach Alternative School",
"Yakima Online",
"Shoreline-Monroe High School",
"Washington Network for Innovative Careers",
"Career Academy at Truman High School",
"Chiawana High School",
"Three Rivers Home Link",
"I-TRACC",
"Aspire Middle School",
"Northwest Career & Technical Academy",
"Science and Math Institute",
"First Creek Middle School",
"Crossroads High School",
"Pierce County Skills Center",
"Puget Sound High School",
"Hazel Wolf K-8",
"Cap Sante High School",
"Columbia Virtual Academy - Kettle Falls",
"Tacoma Business Academy",
"Tacoma Pierce County Education Center",
"Cowlitz Prairie Academy",
"Hoquiam Homelink School",
"Kelso Virtual Academy",
"Washington Virtual Academy Omak Middle School",
"Washington Virtual Academy Omak High School",
"Pacific Cascade Middle School",
"Liberty Middle School",
"Twin Harbors - A Branch of New Market Skills Center",
"Marysville Pilchuck High School",
"West Valley High School Freshman Campus",
"Paideia High School",
"Yakima Satellite Alternative Programs",
"Selkirk Middle School",
"Selkirk High School",
"Selah HomeLink",
"ICCF Ed Program",
"Benton County Jail",
"PEARL",
"Bellevue Big Picture School",
"Easton Secondary School",
"Pacific Virtual Learning",
"Choice",
"Windward High School",
"Lewis River Academy",
"Pacific County Jail",
"Olympia Regional Learning Academy - Montessori School",
"Spokane County Jail",
"On Track Academy",
"Northport Homelink Program",
"Gateway to College",
"Gateway to College",
"Vancouver Contracted Programs",
"Touchstone",
"Seattle Skills Center",
"NW Allprep",
"Yakima Adult Jail",
"Ridgeview Group Home",
"Tesla STEM High School",
"Antioch University Seattle",
"Bates Technical College",
"Bellevue College",
"Bellingham Technical College",
"Big Bend Community College",
"Cascadia Community College",
"Central Washington University",
"Centralia College",
"City University of Seattle",
"Clark College",
"Clover Park Technical College",
"Columbia Basin College",
"Cornish College of the Arts",
"DeVry University Washington",
"DigiPen Institute of Technology",
"Eastern Washington University",
"Edmonds Community College",
"Everett Community College",
"Faith Evangelical College & Seminary",
"Gonzaga University",
"Grays Harbor College",
"Green River Community College",
"Heritage University",
"Highline Community College",
"Lake Washington Institute of Technology",
"Lower Columbia College",
"Northwest College of Art",
"Northwest Indian College",
"Northwest School of Wooden Boat Building",
"Northwest University",
"Olympic College",
"Pacific Lutheran University",
"Peninsula College",
"Pierce College at Fort Steilacoom",
"Pierce College at Puyallup",
"Renton Technical College",
"Saint Martin's University",
"Seattle Community College Central Campus",
"Seattle Community College North Campus",
"Seattle Community College South Campus",
"Seattle Pacific University",
"Seattle University",
"Shoreline Community College",
"Skagit Valley College",
"South Puget Sound Community College",
"Spokane Community College",
"Spokane Falls Community College",
"Tacoma Community College",
"The Evergreen State College",
"University of Phoenix Western Washington Campus",
"University of Puget Sound",
"University of Washington Bothell Campus",
"University of Washington Seattle Campus",
"University of Washington Tacoma Campus",
"Walla Walla Community College",
"Walla Walla University",
"Washington State University",
"Wenatchee Valley College",
"Western Washington University",
"Whatcom Community College",
"Whitman College",
"Whitworth University",
"Yakima Valley Community College"
]