#ddev-generated
# MinIO addon for DDEV - Proxy ports 10101 and 9090
services:
  minio:
    environment:
      MINIO_SERVER_URL: ${DDEV_PRIMARY_URL}:10101
      MINIO_BROWSER_REDIRECT_URL: ${DDEV_PRIMARY_URL}:9090
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: "9089:9090,8999:10101"
      HTTPS_EXPOSE: "9090:9090,10101:10101"
