# FIXME: delete
name: Dev - Fly Deploy
on:
  push:
    branches:
      - dev
concurrency: 
  group: ${{ github.workflow }}
env:
  FLY_API_TOKEN: ${{ secrets.DEV_FLY_DEPLOY_TOKEN }}
jobs:
  deploy:
      name: Deploy apps
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        # - uses: superfly/flyctl-actions/setup-flyctl@master
        # - run: flyctl version
        # - run: make deploy-dev FLY_DEPLOY_FLAGS=--remote-only
